/* Project: Elite Academy - Level 2 (Data Processing & Advanced SQL)
   Author: Shouq Alharthi
   Description: Advanced operations including data standardization, CRUD, aggregations, and performance analysis tables.
   Version: 2
*/

-- 1. Database Usage
USE elite_academy;

-- 2. Schema Refactoring
-- Renaming table for better naming consistency with other tables
RENAME TABLE academy_subjects TO subjects;

-- 3. Data Seeding (Students)
-- Inserting records without IDs or Emails (Auto-generated by the system)
INSERT INTO students (student_name, birth_date, gender, enrollment_date, academic_level, track, gpa) 
VALUES ('Nura Rakan', '2008-05-15', 'F', CURDATE(), 6, 'Scientific', 100),
       ('Fahad Rayan', '2010-02-20', 'M', CURDATE(), 1, 'Humanitarian', 55),
       ('Sara Yazeed', '2009-11-10', 'F', CURDATE(), 2, 'Scientific', 58);

-- 4. Data Standardization (Emails)

-- Temporarily disable safe updates to allow full-table modifications
SET SQL_SAFE_UPDATES = 0;              

-- Students Format: (firstnameID@academy.com)
UPDATE students 
SET email = LOWER(CONCAT(SUBSTRING_INDEX(student_name, ' ', 1), student_id, '@academy.com')); 

-- Teachers Default Format: (firstname.lastname_initial@academy.com)
UPDATE teachers 
SET email = LOWER(CONCAT(SUBSTRING_INDEX(teacher_name, ' ', 1), '.', SUBSTRING(SUBSTRING_INDEX(teacher_name, ' ', -1), 1, 1), '@academy.com'));

-- Customizing specific teacher emails
-- Teacher ID 2 Format: (firstname.lastname@academy.com)
UPDATE teachers 
SET email = LOWER(CONCAT(REPLACE(teacher_name, ' ', '.'), '@academy.com')) 
WHERE teacher_id = 2;

-- Teacher ID 3 Format: (firstname_initial.lastname@academy.com)
UPDATE teachers 
SET email = LOWER(CONCAT(SUBSTRING(teacher_name, 1, 1), '.', SUBSTRING_INDEX(teacher_name, ' ', -1), '@academy.com')) 
WHERE teacher_id = 3;

-- 5. Creating Specialized Tables
CREATE TABLE top_students AS 
SELECT * FROM students 
WHERE gpa > 90;

CREATE TABLE struggling_students AS 
SELECT * FROM students 
WHERE gpa < 60;

-- 6. Advanced Data Retrieval
-- Display students whose names start with 'A'
SELECT student_name 
FROM students 
WHERE student_name LIKE 'A%';

-- 7. Aggregate & Numeric Functions
-- Calculating GPA statistics with descriptive aliases
SELECT 
    AVG(gpa) AS "Average_GPA", 
    MAX(gpa) AS "Max_GPA", 
    MIN(gpa) AS "Min_GPA"
FROM students; 

-- Calculating the overall average GPA and rounding down to the nearest integer    
SELECT FLOOR(AVG(gpa)) AS "Rounded_Average" 
FROM students;

-- 8. Target Filtering (Level & Age Criteria)
-- Identifying Level 6 students with a perfect GPA of 100
SELECT * FROM students 
WHERE academic_level = 6 
AND gpa = 100;

-- Identifying Level 1 students aged between 15 and 16 years
SELECT student_name, birth_date 
FROM students 
WHERE academic_level = 1 
AND TIMESTAMPDIFF(YEAR, birth_date, CURDATE()) BETWEEN 15 AND 16;

-- Counting the total number of students in Academic Level 2
SELECT COUNT(*) AS "Total_Level_2_Students" 
FROM students 
WHERE academic_level = 5;

-- 9. Distinct Data & String Formatting
SELECT DISTINCT track 
FROM students;

SELECT UPPER(subject_name) 
FROM subjects;

-- 10. Data Transformation (Gender Standardization)
-- Expanding ENUM constraints to support full-word gender labels
ALTER TABLE students 
MODIFY COLUMN gender ENUM('M', 'F', 'Male', 'Female') NOT NULL;

-- Standardizing gender records: converting 'F' to 'Female' and 'M' to 'Male'
UPDATE students 
SET gender = CASE 
    WHEN gender = 'F' THEN 'Female' 
    WHEN gender = 'M' THEN 'Male' 
    ELSE gender 
END;

-- 11. Conditional Data Updates
UPDATE students 
SET gpa = gpa + 5 
WHERE gpa < 60;

-- Restore SQL_SAFE_UPDATES to default
SET SQL_SAFE_UPDATES = 1;
